#cloud-config
preserve_hostname: false
hostname: ${hostname}
ssh_pwauth: true
disable_root: false

package_update: ${package_update}
package_upgrade: ${package_upgrade}
packages:
%{ for package in packages ~}
- "${package}"
%{ endfor ~}

${yamlencode(runcmd)}
${yamlencode(write_files)}

users:
  - name: ${ssh_user}
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/${ssh_user}
    shell: /bin/bash
    lock_passwd: false
    ssh_authorized_keys:
    %{ for key in ssh_authorized_keys ~}
    - "${key}"
    %{ endfor ~}


chpasswd:
  expire: false
  users:
    - name: root
      password: pass
      type: text
    - name: ${ssh_user}
      password: ${ssh_pass}
      type: text
